LPD-40537 Fixing symlinks after downloadNode even when cached
When the result of the downloadNode task was cached the logic to fix the
symlinks was not run and therefore npm was failing with the error below.

With these changes we fix the symlinks in a separate task that runs
right after downloadNode even if it has been cached.

The actual root cause is that when the build folder is restored from
the cache, the symlinks are not respected. See
https://github.com/gradle/gradle/issues/3525.

--------------------------------------------------------------------

Unable to generate client JS: node:internal/modules/cjs/loader:1031
Unable to generate client JS:   throw err;
Unable to generate client JS:   ^
Unable to generate client JS:
Unable to generate client JS: Error: Cannot find module '../lib/cli.js'
Unable to generate client JS: Require stack:
Unable to generate client JS: - /home/alex/Projects/liferay/liferay-portal/build/node/bin/npm
Unable to generate client JS:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
Unable to generate client JS:     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
Unable to generate client JS:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Unable to generate client JS:     at require (node:internal/modules/cjs/helpers:119:18)
Unable to generate client JS:     at Object.<anonymous> (/home/alex/Projects/liferay/liferay-portal/build/node/bin/npm:2:1)
Unable to generate client JS:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Unable to generate client JS:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Unable to generate client JS:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Unable to generate client JS:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Unable to generate client JS:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
Unable to generate client JS:   code: 'MODULE_NOT_FOUND',
Unable to generate client JS:   requireStack: [ '/home/alex/Projects/liferay/liferay-portal/build/node/bin/npm' ]